### PR TITLE
Add installation of pip metadata files

### PR DESCRIPTION
**Pull request by traversaro**
When the casadi python library is installed by conda-forge, it is not listed by `pip list` .

This is not problematic until a user tries to install a Python library that depends on `casadi` via  `pip install .` . In that case, the Python `casadi` package already available in the system is ignored, and the PyPI version of casadi is installed itself. 

Even if the users tries to install the library that depends on casadi with `pip install --no-deps .`, then `pip check` would fail with:
~~~
libraryname 0.1.0 requires casadi, which is not installed.
~~~

This PR fixes this problem by backporting the PR https://github.com/casadi/casadi/pull/2878 and passing the related CMake options to install the correct metadata, as described in:
* https://packaging.python.org/specifications/recording-installed-packages/
* https://packaging.python.org/en/latest/specifications/core-metadata/#core-metadata

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge/casadi the PR is ready for review.

**Review by pariterre — APPROVED** [review]
LGTM

**Comment by pariterre** [comment]
@pstjohn 
I let you merge (since I am not a Casadi developper)! If there is no respond before the end of the week, @traversaro you can ping me I'll merge anyway :)

**Comment by traversaro** [comment]
> @pstjohn I let you merge (since I am not a Casadi developper)! If there is no respond before the end of the week, @traversaro you can ping me I'll merge anyway :)

Friendly ping, thanks!

**Comment by pstjohn** [comment]
whoops, happy to merge this (and add you as a maintainer going forward if that makes this go faster.) I haven't done much work with casadi recently.

**Comment by traversaro** [comment]
> and add you as a maintainer going forward if that makes this go faster

Thanks, I opened a PR for this in https://github.com/conda-forge/casadi-feedstock/pull/62 .

**Pull request merged**
