### PR TITLE
adding qpoases and blocksqp

### PR DESCRIPTION
**Pull request by pstjohn**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adding build arguments for qpoases and blocksqp, addresses #21

### CODE REVIEW

**Comment by pstjohn** [comment]
this is failing on the test with a mumps error. It's odd, since those same packages are installed during the build phase without issue

```
    mumps:           5.0.1-0                 conda-forge
    mumps-include:   5.1.2-1007              conda-forge
    mumps-seq:       5.1.2-h0ae83f2_1007     conda-forge
    ncurses:         6.1-hf484d3e_1002       conda-forge
    numpy:           1.16.3-py36he5ce36f_0   conda-forge
    openblas:        0.2.18-6                conda-forge
    openssl:         1.1.1b-h14c3975_1       conda-forge
    python:          3.6.7-h381d211_1004     conda-forge
    readline:        7.0-hf8c457e_1001       conda-forge
    scotch:          6.0.6-h491eb26_1002     conda-forge
    sqlite:          3.26.0-h67949de_1001    conda-forge
    tk:              8.6.9-h84994c4_1001     conda-forge
    xz:              5.2.4-h14c3975_1001     conda-forge
    zlib:            1.2.11-h14c3975_1004    conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ERROR:conda.stderr:
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::mumps-include-5.1.2-1007, conda-forge::mumps-5.0.1-0
  path: 'include/cmumps_c.h'
```

**Comment by pstjohn** [comment]
@conda-forge-admin, please rerender

**Comment by pstjohn** [comment]
Looks like I'm getting syntax errors on the packaging step. 

For python3 builds:
```
Packaging casadi
INFO:conda_build.build:Packaging casadi
Packaging casadi-3.4.5-py37hbd7caa9_1004
INFO:conda_build.build:Packaging casadi-3.4.5-py37hbd7caa9_1004
compiling .pyc files...
  File "lib/python3.7/site-packages/casadi/tools/structure.py", line 271
    raise new_exc.__class__, new_exc, tb
                           ^
SyntaxError: invalid syntax
```

and for python 2 builds:
```
Packaging casadi
INFO:conda_build.build:Packaging casadi-3.4.5-py27h09a28d5_1004
Packaging casadi-3.4.5-py27h09a28d5_1004
compiling .pyc files...
  File "lib/python2.7/site-packages/casadi/tools/structure3.py", line 274
    raise Exception("Error occured in entry context with powerIndex %s, at canonicalIndex %s" % (str(powerIndex),str(canonicalIndex))) from e
                                                                                                                                          ^
SyntaxError: invalid syntax
```

**Comment by pariterre** [comment]
@pstjohn 
Do you want to keep this PR open?

**Comment by pstjohn** [comment]
I can close it, I don't really have the time to work on this

**Pull request closed without merging**
