### PR TITLE
clang compilation on OS X

### PR DESCRIPTION
**Pull request by pstjohn**
This PR will be to update casadi to use the new IPOPT recipe (with clang), and update the compiler to use the toolchain

### CODE REVIEW

**Comment by bluescarni** [comment]
I think for the linux build you need that ``yum_requirements.txt`` file @isuruf mentioned in the ipopt PR.

**Comment by isuruf** [comment]
Or we could patch `ipopt.pc` and remove `-lgfortran` from it.

**Comment by pstjohn** [comment]
Hmm, added the yum_requirements.txt file but it doesn't seem to be picking it up.

**Comment by isuruf** [comment]
You'll need to do a rerendering. I think we should fix `ipopt.pc` instead of requiring `gfortran` in all of the downstream projects.
I'm not familiar with ipopt, but do you know whether the dependencies are needed in the header files of ipopt? If not, `ipopt.pc` should be fixed to reflect that.

**Comment by pstjohn** [comment]
But ipopt already requires gfortran? So wouldn't this be a downstream project that requires it?

The source for ipopt is here: https://github.com/coin-or/Ipopt/. it looks like there are some compilation flags that deal with a missing fortran compiler, so I would expect that the fortran links aren't in the header files.. Worth a try at least.

should we fix ipopt.pc in this recipe or in ipopt-feedstock? The line in that file we'll need to patch has a lot of build-dependent info in it. Probably would have to do some sort of `sed`. For a test install at least, this is what it looked like on my machine:

```
prefix=/Users/pstjohn/anaconda3/conda-bld/ipopt_1493384828718/_t_env
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include/coin

Name: IPOPT
Description: Interior Point Optimizer
URL: https://projects.coin-or.org/Ipopt
Version: 3.12.7
Libs: -L${libdir} -lipopt -Wl,-rpath,/Users/pstjohn/anaconda3/conda-bld/ipopt_1493384828718/_t_env/lib -L/Users/pstjohn/anaconda3/conda-bld/ipopt_1493384828718/_t_env/lib -ldmumps -lmumps_common -lpord -lmpiseq -lesmumps -lscotch -lscotcherr -lmetis -lgfortran -Wl,-rpath,/Users/pstjohn/anaconda3/conda-bld/ipopt_1493384828718/_t_env/lib -L/Users/pstjohn/anaconda3/conda-bld/ipopt_1493384828718/_t_env/lib -lopenblas -Wl,-rpath,/Users/pstjohn/anaconda3/conda-bld/ipopt_1493384828718/_t_env/lib -L/Users/pstjohn/anaconda3/conda-bld/ipopt_1493384828718/_t_env/lib -lopenblas -lm  -ldl
Cflags: -I${includedir}
Requires:
```

**Comment by isuruf** [comment]
```
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@/coin

Name: IPOPT
Description: Interior Point Optimizer
URL: https://projects.coin-or.org/Ipopt
Version: @PACKAGE_VERSION@
Libs: -L${libdir} -lipopt @IPOPTLIB_PCLIBS@
Cflags: -I${includedir}
Requires: @IPOPTLIB_PCREQUIRES@
```
should probably be changed to
```
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@/coin

Name: IPOPT
Description: Interior Point Optimizer
URL: https://projects.coin-or.org/Ipopt
Version: @PACKAGE_VERSION@
Libs: -L${libdir} -lipopt
Libs.private: @IPOPTLIB_PCLIBS@
Cflags: -I${includedir}
Requires: @IPOPTLIB_PCREQUIRES@
```

gfortran is a dependency, yes, but downstream projects need not link to it directly.

**Comment by pstjohn** [comment]
Awesome, thanks for the help @isuruf! I'll try again when the other PR passes.
I'll also ping @tkralphs who's the ipopt expert just in case this is a huge mistake 😄

**Comment by pstjohn** [comment]
More gfortran issues... Looks like both openblas and ipopt are expecting symbols from gfortran on linux.

```
[100%] Linking CXX executable ../../../../bin/ctemplate
cd /feedstock_root/build_artefacts/casadi_1493397275735/work/casadi-3.1.1/build/docs/api/examples/ctemplate && /feedstock_root/build_artefacts/casadi_1493397275735/_b_env/bin/cmake -E cmake_link_script CMakeFiles/ctemplate.dir/link.txt --verbose=0
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: warning: libgfortran.so.3, needed by /feedstock_root/build_artefacts/casadi_1493397275735/_b_env/lib/libopenblas.so, not found (try using -rpath or -rpath-link)
/feedstock_root/build_artefacts/casadi_1493397275735/_b_env/lib/libopenblas.so: undefined reference to `_gfortran_concat_string@GFORTRAN_1.0'
```

**Comment by isuruf** [comment]
That should have been
```
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@/coin

Name: IPOPT
Description: Interior Point Optimizer
URL: https://projects.coin-or.org/Ipopt
Version: @PACKAGE_VERSION@
Libs: -L${libdir} -lipopt -Wl,-rpath,${libdir}
Libs.private: @IPOPTLIB_PCLIBS@
Cflags: -I${includedir}
Requires: @IPOPTLIB_PCREQUIRES@
```
Sorry about that.

**Comment by isuruf** [comment]
Or you can do it in this repo as well. Add the following at the beginning of build.sh
`export LDFLAGS="${LDFLAGS} -Wl,-rpath,${PREFIX}/lib`

**Comment by pstjohn** [comment]
Eh, easy enough to do in conda-forge/ipopt-feedstock#8

**Comment by pstjohn** [comment]
Still getting the same error. I thought rpath helped you with the runtime dependencies, but the errors are happening during the build phase. (the pkgconfig file won't change the runtime dependencies of the ipopt libraries)

**Comment by pstjohn** [comment]
trying yum_requirements again...  ¯\_(ツ)_/¯

**Comment by pstjohn** [comment]
Ok, so now I'm not getting the gfortran errors, but ipopt isn't carrying around the additional libraries it needs:

```
[100%] Linking CXX executable ../../../bin/rocket_single_shooting
cd /feedstock_root/build_artefacts/casadi_1493410204905/work/casadi-3.1.1/build/docs/examples/cplusplus && /feedstock_root/build_artefacts/casadi_1493410204905/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/cmake -E cmake_link_script CMakeFiles/rocket_single_shooting.dir/link.txt --verbose=0
/opt/rh/devtoolset-2/root/usr/libexec/gcc/x86_64-redhat-linux/4.8.2/ld: warning: libmetis.so, needed by /feedstock_root/build_artefacts/casadi_1493410204905/
```

I'm thinking I need to revert the ipopt feedstock changes to keep the pkg-config flags...

**Comment by isuruf** [comment]
https://github.com/pstjohn/casadi-feedstock/pull/1

**Comment by pstjohn** [comment]
Awesome, looks like we needed rpath-link instead of rpath. Merging this is favor of the other options.

**Comment by tkralphs** [comment]
I didn't delve into the details deeply enough to tease out why `-lgofrtran` was not found when linking, but as far as the possible problem in the `.pc` file, I guess we should fix that in the Ipopt repo rather than patching. The reason why those libraries are included in `Libs` is because of some stuff we were doing in our build system historically that wasn't quite best practice. This has now been mostly fixed up. 

In particular, we used to link our shared libraries without the `--no-undefined` flag, which meant that all dependencies _did_ have to be linked explicitly. We now link dependent libraries explicitly with `--no-undefined`, so the additional libs are not required. I'll put on the TODO list to fix this, but since I want to keep all the COIN-OR building and linking the same way, the change will need to be propogated to all the projects in the optimization suite.

Thanks for the catch! cc'ing @svigerske

**Comment by svigerske** [comment]
@tkralphs I agree that the change makes sense and is more correct if one builds with `--enable-dependency-linking`, which is the default. But I'm still hesitating to make changes like this to the current Ipopt/trunk, etc. I'm just afraid that something will break, e.g., the non-pkg-config build. Also if one configures with `--disable-dependency-linking`, then one would need to have everything in `Libs` again.
I would prefer to delay this change to the .pc file until we switch to the newer BuildTools / autotools.

**Comment by pstjohn** [comment]
Thanks for weighing in!

On lgfortran, that was probably a conda issue. Ipopt's pkgconfig was asking for -lgfortran, but isuruf advised against explicitly linking against it. When I get a chance I'll try another PR where I remove the yum-requirements from this recipe to see if we're able to link against IPOPT without explicitly installing lgfortran first.

I don't think the patch is the worst way to go about this, we can certainly drop it in future versions (like we should probably currently do with the mumps.h lines). I suppose it does mean that a conda-installed ipopt will have a different pkg-config behavior than one from homebrew or elsewhere though.

**Pull request merged**
