### PR TITLE
Add osx-arm64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Fix #56

**Comment by traversaro** [comment]
I think we need to move swig from `host` to `build` dependencies, I had a similar failure in https://github.com/conda-forge/idyntree-feedstock/pull/26 .

**Comment by Tobias-Fischer** [comment]
This is ready to go @conda-forge/casadi

**Comment by Tobias-Fischer** [comment]
Kind ping @pstjohn @pariterre

**Pull request merged**
