### PR TITLE
Unpin numpy

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by pstjohn** [comment]
I'll probably close this in favor of a more general update to casadi 3.3. Although this repo is needed less now that casadi supports a pip install

**Comment by jschueller** [comment]
These two things are totally independent. Besides this saves a lot of ci time.

**Comment by pstjohn** [comment]
casadi 3.3 no longer depends on numpy at compile time

**Comment by jschueller** [comment]
You'll have to rerender anyways.

**Pull request closed without merging**
