### PR TITLE
Enable OSX ARM64

### PR DESCRIPTION
**Pull request by jcarpent**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
Should wait for https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=366489&view=results

**Comment by traversaro** [comment]
I am afraid this requires ipopt for arm macOS.

**Comment by jcarpent** [comment]
Thanks @traversaro. I've just seen that. I've just opened a PR on ipopt feedstock: https://github.com/conda-forge/ipopt-feedstock/pull/72

**Comment by jcarpent** [comment]
This requires a lot of dependencies to be fixed.
Yet, I've opened in #57 an issue concerning the splitting of casadi and casadi-ipopt to make the dependency graph lighter and more flexible.

**Comment by traversaro** [comment]
> Thanks @traversaro. I've just seen that. I've just opened a PR on ipopt feedstock: https://github.com/conda-forge/ipopt-feedstock/pull/72

That was actually handled by the migration bot, but it is itself blocked on some dependencies, see  https://conda-forge.org/status/#armosxaddition for more info.

**Comment by jcarpent** [comment]
Do we really need ipopt as a strong dependency of casadi?

**Comment by Tobias-Fischer** [comment]
Hi @jcarpent @traversaro, I'm interested in the status of this PR and #57. Have you got any more thoughts on it? I had a look at ampl-mp, and it's not easy to build for osx-arm64, so ipopt will not be easy either. Is mumps also optional?

**Comment by traversaro** [comment]
> Do we really need ipopt as a strong dependency of casadi?

Related issue: https://github.com/conda-forge/casadi-feedstock/issues/57 . In a nutshell, a quick solution is to disable the ipopt dependency may be helpful in the short term for osx-arm64, but in general it may be useful to move the casadi ipopt plugin to a completly separate package to not force ipopt dependency to downstream packages that only depend on core casadi. 

> Is mumps also optional?

If I recall correctly, in theory mumps is an optional dependency of ipopt, but in practice is the only linear solver currently available on conda-forge, so without it ipopt will not work.

**Comment by Tobias-Fischer** [comment]
I built all dependencies as well as casadi (natively on a M1) and uploaded it to https://anaconda.org/tobiasrobotics/

**Comment by Tobias-Fischer** [comment]
See #60 instead

**Comment by traversaro** [comment]
Fixed by https://github.com/conda-forge/casadi-feedstock/pull/60 .

**Pull request closed without merging**
