### PR TITLE
Trying to compile for windows

### PR DESCRIPTION
**Pull request by pariterre**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pariterre** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Thanks a lot @pariterre ! To start, I guess that we need to enable the WITH_PYTHON, WITH_PYTHON3 and WITH_IPOPT CMake options in https://github.com/conda-forge/casadi-feedstock/blob/master/recipe/bld.bat#L11 . Furthermore, looking at the installation log it seems that C++ include and libraries are installed in non-standard directories, so you may want to also manually set the `INCLUDE_PREFIX`, `CMAKE_PREFIX`, `LIB_PREFIX` and `BIN_PREFIX` CMake variables to the appropriate directories, as done for example in https://github.com/robotology/robotology-vcpkg-ports/blob/master/casadi/portfile.cmake#L14 .

**Comment by pariterre** [comment]
There it is,
but the problem is similar to what I had before, it cannot find IPOPT for some reason..

**Comment by traversaro** [comment]
> There it is,
> but the problem is similar to what I had before, it cannot find IPOPT for some reason..

I guess we need to fix the ipopt .pc file generation in the ipopt feedstock, or just patch Casadi's FindIpopt cmake script to search for ipopt with find_file and find_package if the pkg-config search fails.

**Comment by traversaro** [comment]
> 
> 
> > There it is,
> > but the problem is similar to what I had before, it cannot find IPOPT for some reason..
> 
> I guess we need to fix the ipopt .pc file generation in the ipopt feedstock, or just patch Casadi's FindIpopt cmake script to search for ipopt with find_file and find_package if the pkg-config search fails.

To clarify, this is already tracked in https://github.com/conda-forge/ipopt-feedstock/issues/56, and I am currently waiting for https://github.com/conda-forge/ipopt-feedstock/pull/59 to be merged to fix it.

**Comment by traversaro** [comment]
The .pc files installed by ipopt should be fixed by https://github.com/conda-forge/ipopt-feedstock/pull/60 .

**Comment by pariterre** [comment]
@traversaro 
Allright, waiting for the merge and then I try to rebuild!

**Comment by traversaro** [comment]
> 
> 
> @traversaro
> Allright, waiting for the merge and then I try to rebuild!

Merged.

**Comment by pariterre** [comment]
@traversaro 
Still seems not to find Ipopt...

**Comment by traversaro** [comment]
I guess something strange is happening in https://github.com/casadi/casadi/blob/3.5.5/cmake/FindIPOPT.cmake#L10 . To debug, I added a print in https://github.com/pariterre/casadi-feedstock/pull/1, can you merge it? Thanks!

**Comment by traversaro** [comment]
> 
> 
> I guess something strange is happening in https://github.com/casadi/casadi/blob/3.5.5/cmake/FindIPOPT.cmake#L10 . To debug, I added a print in [pariterre#1](https://github.com/pariterre/casadi-feedstock/pull/1), can you merge it? Thanks!

The issue is not in CMake, it is really that pkg-config does not find ipopt, on a custom local environment I get:
~~~
(ipopt) C:\Users\STraversaro>pkg-config --exists --print-errors --debug ipopt
Error printing disabled by default due to use of output options --exists, --atleast/exact/max-version, --list-all or no output option at all. Value of --print-errors: 1
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Looking for package 'ipopt'
Looking for package 'ipopt-uninstalled'
Reading 'ipopt' from file 'C:\Users\STraversaro\Miniforge3\envs\ipopt\Library\lib\pkgconfig\ipopt.pc'
Parsing package file 'C:\Users\STraversaro\Miniforge3\envs\ipopt\Library\lib\pkgconfig\ipopt.pc'
  line>prefix=C:/Users/STraversaro/Miniforge3/envs/ipopt/Library
 Variable declaration, 'prefix' overridden with 'C:/Users/STraversaro/Miniforge3/envs/ipopt/Library'
  line>exec_prefix=${prefix}
 Variable declaration, 'exec_prefix' has value 'C:/Users/STraversaro/Miniforge3/envs/ipopt/Library'
  line>libdir=C:/Users/STraversaro/Miniforge3/envs/ipopt/Library/lib
 Variable declaration, 'libdir' has value 'C:/Users/STraversaro/Miniforge3/envs/ipopt/Library/lib'
  line>includedir=C:/Users/STraversaro/Miniforge3/envs/ipopt/Library/include/coin-or
 Variable declaration, 'includedir' has value 'C:/Users/STraversaro/Miniforge3/envs/ipopt/Library/include/coin-or'
  line>
  line>Name: IpOpt
  line>Description: Interior Point Optimizer
  line>URL:
  line>Version: 3.13.3
  line>Cflags: -I${includedir}
  line>Libs: -L${libdir} -lipopt
Path position of 'ipopt' is 1
Adding 'ipopt' to list of known packages
~~~
while in the build is not working. I added a few more debug prints in https://github.com/pariterre/casadi-feedstock/pull/2 .

**Comment by traversaro** [comment]
This is strange, everything seems ok with ipopt, it just seems that the ipopt.pc files is not installed for some reason, even if the build number is indeed 7, I added a few more prints in https://github.com/pariterre/casadi-feedstock/pull/3 .

**Comment by traversaro** [comment]
I think there is some kind of strange relation between the host environment and the build environment. pkg-config is installed in the host environment, while pkg-config in the build environment. I hope that https://github.com/pariterre/casadi-feedstock/pull/4 will be sufficient to fix the problem (inspired by similar code snippets across conda-forge: https://github.com/search?q=org%3Aconda-forge+PKG_CONFIG_PATH&type=code ).

**Comment by pariterre** [comment]
@traversaro 
I kind of been there done that before... I finally gave up... I really hope you can find a solution !

**Comment by traversaro** [comment]
> 
> 
> @traversaro
> I kind of been there done that before... 

In which sense? Did you already  reached this point? 

> I finally gave up... I really hope you can find a solution !

Ack, I think just  few CMake tweaks are probably missing (the error seems related to the fact that in https://github.com/casadi/casadi/blob/3.5.5/CMakeLists.txt#L900 the case in which "CMAKE_INSTALL_PREFIX" and "CMAKE_PREFIX" are the same directory is not proplerly handled, I can pick up the PR in one of the next weekends.

**Comment by pariterre** [comment]
> In which sense? Did you already reached this point?

Nope! I got as far as it got when I first added back Windows for this very PR! It's just that I feel a bit clueless..

I am waiting for your next PR to my fork!

**Pull request merged**
